{{- range $job := .Values.jobs }}
  {{- /* Check if serviceAccount.name is not provided */}}
  {{- if not (and (hasKey $job "serviceAccount") (hasKey $job.serviceAccount "name")) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if and (hasKey $job "serviceAccount") (hasKey $job "serviceAccount.name") }}
  name: {{ $job.serviceAccount.name }}
  {{- else }}
  name: {{ $job.name }}
  {{- end }}
  labels:
    {{- include "cronjob.labels" $ | nindent 4 }}
    cron: {{ $job.name }}
  {{- if and (hasKey $job "serviceAccount") (hasKey $job "serviceAccount.annotations") }}
  {{- with $job.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
