apiVersion: v1
kind: Secret
metadata:
  name: {{ template "charge-lnd.name" . }}-secret
  annotations:
  {{- if .Values.vault.enabled }}
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    vault.security.banzaicloud.io/vault-serviceaccount: {{ template "charge-lnd.serviceAccountName" . }}
    vault.security.banzaicloud.io/vault-role: {{ .Values.vault.role }}
    {{- range $key, $value := .Values.vault.extraAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end}}
  labels:
{{ include "charge-lnd.labels" . | indent 4 }}
stringData:
{{- if .Values.configuration.secrets.lndCertificate }}
  lndCertificate: "{{ .Values.configuration.secrets.lndCertificate }}"
{{- end}}
{{- if .Values.configuration.secrets.lndMacaroon }}
  lndMacaroon: {{ .Values.configuration.secrets.lndmacaroon }}
{{- end}}