{{- if .Values.backstage.appConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: backstage-app-config
  {{- if .Values.commonAnnotations }}
  annotations:
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
stringData:
  app-config.yaml: |
    {{- include "common.tplvalues.render" ( dict "value" .Values.backstage.appConfig "context" $) | nindent 4 }}
{{- end }}
